global:
  name: Presto Landscape
  short_name: Presto
  repo: prestodb/presto-landscape
  website: https://landscape.prestodb.io
  short_domain: l.prestodb.io
  company_url: https://prestodb.io
  email: info@graphql.foundation
  self: https://www.crunchbase.com/organization/presto-foundation
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: Presto Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@prestodb'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Presto Foundation Member
  flags:
    companies: Presto Foundation Member
    hide_license_for_categories:
      - Presto Adopter
      - Presto Foundation Member
twitter:
  search: landscape.prestodb.io
  url: https://landscape.prestodb.io
  text: Presto Landscape
relation:
  label: Presto Relation
  url: presto
  values:
    - id: hosted
      label: Presto Foundation Projects
      children:
        - id: foundationproject
          label: Presto Foundation Projects
          prefix: Presto
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Presto Foundation Project
          big_picture_color: rgb(24,54,114)
    - id: company
      label: Presto Foundation Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: Presto Foundation Member Products/Projects
      tag: Presto Foundation Member
    - id: false
      label: Non-Presto Foundation Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: Presto
    label: Member
    funding: Premier
    is_large: true
  Executive Premier:
    name: Presto
    label: Member
    funding: Executive Premier
    is_large: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Presto Landscape</h1> The Presto Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=graphql_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Presto Landscape
    fullscreen_header: See the interactive landscape at l.prestodb.io
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 605
        height: 120
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Services
        rows: 3
        width: 325
        height: 120
        top: 0
        left: 645
        color: rgb(79,121,13)
        fit_width: true
      - type: HorizontalCategory
        category: Presto Adopter
        rows: 6
        width: 970
        height: 180
        top: 140
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Presto Foundation Member
        rows: 4
        width: 650
        height: 160
        top: 340
        left: 0
        color: rgb(103,66,18)
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 160
        top: 340
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Presto community, and also shows the member organizations of the Presto Foundation.
            top: 55
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.prestodb.io
            top: 100
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 90
            right: 100
            top: 15
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 80
            right: 10
            top: 10
            title: Presto Foundation Logo
test:
  header: Presto Landscape
  section: Presto Foundation Member
  logo: intel-member.svg
